[package]
name = "snake"
version = "0.1.0"
edition = "2024"

[dependencies]
abi = { path = "../../abi" }
embedded-graphics = "0.8.1"
embedded-snake = { path = "../../../embedded-snake-rs" }
rand = { version = "0.9.0", default-features = false }
