[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[features]
default = []
defmt = ["dep:defmt"]

[dependencies]
abi_sys = { path = "../abi_sys" }
bitflags = "2.9.4"
defmt = { version = "0.3", optional = true }
